version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"
  apt_packages:
    - libldap2-dev
    - libsasl2-dev
  jobs:
    pre_install:
      - pip install --upgrade pip
      - pip install uv
      - uv venv
      - uv pip install --group docs
    build:
      html:
        - uv run python -m mkdocs build --clean --site-dir $READTHEDOCS_OUTPUT/html --config-file mkdocs.yml

mkdocs:
   configuration: mkdocs.yml
